services:
 dynamodb-local:
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal
   networks:
     - backend

networks:
  backend:
    name: dynamodb-local
